### ISSUE TITLE
doesn't work in DIM production anymore 

### ISSUE THREAD

**Issue by phixion** [HZDeluxe/light-gg-linking-for-DIM#1]
Seems it stopped working on 

https://app.destinyitemmanager.com/ , however https://beta.destinyitemmanager.com/ 

is fine

**Comment by HirotaZX** [comment]
Try refreshing the page after the inventory is loaded?
This may be a known bug related to URL matching, I'll fix it later.

Oh, It looks like some html structure of DIM was changed, I'll fix it.

**Comment by HirotaZX** [comment]
You can try to update this script to 0.1.1 in your userscript manager, it should work now.

**Comment by phixion** [comment]
Perfect! Works like it did before.

Thanks for your quick support
