### ISSUE TITLE
脚本由于DIM最近的更新已失效

### ISSUE THREAD

**Issue by PaiJi** [HZDeluxe/light-gg-linking-for-DIM#3]
`const itemNameElm = itemPopup.querySelector('a[href^="https://destinytracker.com/"]');`
由于DIM现在点击物品标题的时候会开一个Dialog直接展示物品详情，所以这里 itemNameElm 似乎拿不到值返回null了

**Comment by flyhaozi** [comment]
Dialog里已经有light.gg链接了，感觉脚本存在的意义不大了😂，不过我还是会尝试修复一下

**Comment by HirotaZX** [comment]
Dialog里已经有light.gg的链接了，感觉脚本没什么必要了😂，不过我还是会尝试修复下

**Comment by HirotaZX** [comment]
已经修复了，可以在用户脚本管理器里进行更新

**Comment by PaiJi** [comment]
谢谢作者XD
